package ru.courier.money;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.DecimalFormat;
import java.util.*;

public class MainActivity extends Activity {
    private static final String PREFS="courier_money", ORDERS="orders";
    private static final String PICKUP="pickup_fee", DELIVERY="delivery_fee", PKM="price_per_km", PKG="price_per_kg", RATING="rating", R5="rating_5", R475="rating_475", R450="rating_450", R425="rating_425";
    private final ArrayList<Order> orders=new ArrayList<>();
    private final DecimalFormat money=new DecimalFormat("0.##"), kmFmt=new DecimalFormat("0.000"), meterFmt=new DecimalFormat("0");
    private SharedPreferences prefs; private LinearLayout list; private TextView summary;
    private double pickup,delivery,perKm,perKg,rating,r5,r475,r450,r425;
    private final Store[] stores={new Store("Пятёрочка №1","проспект Ленина, 20"),new Store("Пятёрочка №2","4-й микрорайон, 21А"),new Store("Пятёрочка №3","ул. Спортивная, 15Б")};

    @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences(PREFS,0); loadSettings(); loadOrders(); build(); refresh();}
    private void loadSettings(){pickup=num(PICKUP,"70");delivery=num(DELIVERY,"105");perKm=num(PKM,"30");perKg=num(PKG,"0");rating=clamp(num(RATING,"5"),0,5);r5=num(R5,"25");r475=num(R475,"20");r450=num(R450,"10");r425=num(R425,"5");}
    private double num(String k,String d){return parse(prefs.getString(k,d),Double.parseDouble(d));}
    private double parse(String s,double f){try{double v=Double.parseDouble((s==null?"":s).trim().replace(',','.'));return Double.isFinite(v)&&v>=0?v:f;}catch(Exception e){return f;}}
    private double clamp(double v,double a,double b){return Math.max(a,Math.min(b,v));}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
    private LinearLayout.LayoutParams mw(){return new LinearLayout.LayoutParams(-1,-2);}
    private LinearLayout.LayoutParams wt(float w){return new LinearLayout.LayoutParams(0,-2,w);}
    private TextView tv(String s,int z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(0,dp(3),0,dp(3));return t;}
    private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(Color.rgb(30,82,140));b.setBackground(bg(Color.rgb(248,250,253),Color.rgb(210,220,232),12));return b;}
    private GradientDrawable bg(int fill,int stroke,int r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));g.setStroke(dp(1),stroke);return g;}
    private EditText field(String hint,boolean decimal){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextSize(16);e.setInputType(decimal?InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL:InputType.TYPE_CLASS_TEXT);return e;}

    private void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(12),dp(16),dp(12));root.setBackgroundColor(Color.rgb(245,247,250));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(16),dp(14),dp(16),dp(14));head.setBackground(bg(Color.rgb(232,240,252),Color.rgb(205,217,232),16));
        TextView h=tv("🚴 Courier Money",26,true);h.setTextColor(Color.rgb(25,39,52));head.addView(h,mw());TextView sub=tv("Учёт заработка курьера",15,false);sub.setTextColor(Color.rgb(76,91,108));head.addView(sub,mw());
        LinearLayout.LayoutParams hp=mw();hp.setMargins(0,0,0,dp(10));root.addView(head,hp);
        LinearLayout actions=new LinearLayout(this);Button add=btn("➕ Заказ");add.setOnClickListener(v->addDialog());actions.addView(add,wt(1));Button set=btn("⚙️ Настройки");set.setOnClickListener(v->settings());actions.addView(set,wt(1));Button clear=btn("🧹 Очистить");clear.setOnClickListener(v->clear());actions.addView(clear,wt(1));root.addView(actions,mw());
        summary=tv("",16,true);summary.setBackground(bg(Color.WHITE,Color.rgb(225,230,236),14));summary.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout.LayoutParams sp=mw();sp.setMargins(0,dp(10),0,dp(8));root.addView(summary,sp);
        root.addView(tv("📋 Заказы",20,true),mw());ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
    }
    private String dist(double v){return meterFmt.format(v*1000)+" м  ("+kmFmt.format(v)+" км)";}
    private double ratingBonus(double r){if(r>=4.995)return r5;if(r>=4.75)return r475;if(r>=4.5)return r450;if(r>=4.25)return r425;return 0;}
    private void refresh(){double total=0,k=0,w=0;for(Order o:orders){total+=o.total;k+=o.km;w+=o.kg;}summary.setText("💵 "+money.format(total)+" ₽\n📦 "+orders.size()+" заказов • 🚗 "+kmFmt.format(k)+" км • ⚖️ "+money.format(w)+" кг\n⚙️ "+money.format(pickup)+" ₽ забор + "+money.format(delivery)+" ₽ доставка + "+money.format(perKm)+" ₽/км + "+money.format(perKg)+" ₽/кг • ⭐ "+String.format(Locale.US,"%.2f",rating));list.removeAllViews();ArrayList<Order> r=new ArrayList<>(orders);Collections.reverse(r);if(r.isEmpty()){list.addView(tv("📭 Пока нет заказов.\nНажми «➕ Заказ».",16,false),mw());return;}for(Order o:r){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(12),dp(14),dp(12));card.setBackground(bg(Color.WHITE,Color.rgb(225,230,236),14));TextView amount=tv("💰 "+money.format(o.total)+" ₽",21,true);amount.setTextColor(Color.rgb(24,108,64));card.addView(amount,mw());card.addView(tv("🏪 "+o.store,15,true),mw());card.addView(tv("📍 "+o.address,15,false),mw());card.addView(tv("🚗 "+dist(o.km),15,false),mw());card.addView(tv("⚖️ "+money.format(o.kg)+" кг • +"+money.format(o.weightBonus)+" ₽",14,false),mw());card.addView(tv((o.multi?"🔗 Мультизаказ":"📦 Обычный")+" • ⭐ "+String.format(Locale.US,"%.2f",o.rating)+" • +"+money.format(o.ratingBonus)+" ₽",14,false),mw());LinearLayout.LayoutParams cp=mw();cp.setMargins(0,dp(6),0,dp(4));list.addView(card,cp);LinearLayout a=new LinearLayout(this);Button edit=btn("✏️ Изменить");edit.setOnClickListener(v->editDialog(o));a.addView(edit,wt(1));Button del=btn("🗑️ Удалить");del.setTextColor(Color.rgb(180,55,55));del.setOnClickListener(v->delete(o));LinearLayout.LayoutParams dpw=wt(1);dpw.setMargins(dp(8),0,0,0);a.addView(del,dpw);list.addView(a,mw());}}

    private void addDialog(){
        final LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),0,dp(18),0);Spinner store=new Spinner(this);ArrayList<String> names=new ArrayList<>();for(Store s:stores)names.add(s.name);store.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,names));box.addView(tv("🏪 Магазин",15,true),mw());box.addView(store,mw());
        LinearLayout rows=new LinearLayout(this);rows.setOrientation(LinearLayout.VERTICAL);box.addView(rows,mw());ArrayList<Row> data=new ArrayList<>();Button addRow=btn("➕ Добавить клиента");
        Runnable add=()->{Row r=new Row();data.add(r);LinearLayout block=new LinearLayout(this);block.setOrientation(LinearLayout.VERTICAL);block.setPadding(0,dp(8),0,dp(4));block.addView(tv("Клиент "+data.size()+(data.size()==1?" (первый)":""),15,true),mw());r.address=field("Адрес клиента",false);r.kg=field("Вес, кг",true);r.km=field("Расстояние, например 945 м или 0.945 км",true);block.addView(r.address,mw());block.addView(r.kg,mw());block.addView(r.km,mw());rows.addView(block,mw());};add.run();addRow.setOnClickListener(v->add.run());box.addView(addRow,mw());
        AlertDialog d=new AlertDialog.Builder(this).setTitle("➕ Новый заказ").setView(box).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(data.isEmpty()){toast("Добавь клиента");return;}Store st=stores[store.getSelectedItemPosition()];for(int i=0;i<data.size();i++){Row r=data.get(i);String ad=r.address.getText().toString().trim();if(ad.isEmpty()){toast("Заполни адрес клиента "+(i+1));return;}double km=parseDistance(r.km.getText().toString(),-1);if(km<0){toast("Проверь километраж клиента "+(i+1));return;}double kg=parse(r.kg.getText().toString(),0);boolean first=i==0;double bonus=first?ratingBonus(rating):0;double total=(first?pickup:0)+delivery+km*perKm+kg*perKg+bonus;orders.add(new Order(total,km,kg,st.name,ad,rating,bonus,kg*perKg,data.size()>1,first));}save();refresh();d.dismiss();}));d.show();
    }
    private double parseDistance(String s,double fallback){if(s==null)return fallback;s=s.trim().toLowerCase(Locale.US).replace(',','.');try{if(s.endsWith("м")||s.endsWith("m")){double m=Double.parseDouble(s.substring(0,s.length()-1).trim());return m>=0?m/1000:fallback;}if(s.endsWith("км"))s=s.substring(0,s.length()-2).trim();if(s.endsWith("km"))s=s.substring(0,s.length()-2).trim();double v=Double.parseDouble(s);return v>=0?v:fallback;}catch(Exception e){return fallback;}}

    private void editDialog(Order o){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),0,dp(18),0);EditText ad=field("Адрес",false);ad.setText(o.address);EditText kg=field("Вес, кг",true);kg.setText(money.format(o.kg));EditText km=field("Расстояние: 945 м или 0.945 км",true);km.setText(kmFmt.format(o.km));box.addView(ad,mw());box.addView(kg,mw());box.addView(km,mw());new AlertDialog.Builder(this).setTitle("✏️ Изменить заказ").setView(box).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",(d,w)->{String a=ad.getText().toString().trim();double k=parseDistance(km.getText().toString(),-1);if(a.isEmpty()||k<0){toast("Проверь адрес и километраж");return;}double g=parse(kg.getText().toString(),0);double bonus=o.multi&&!o.multiFirst?0:ratingBonus(o.rating);double total=(o.multi&&!o.multiFirst?0:pickup)+delivery+k*perKm+g*perKg+bonus;int i=orders.indexOf(o);if(i>=0)orders.set(i,new Order(total,k,g,o.store,a,o.rating,bonus,g*perKg,o.multi,o.multiFirst));save();refresh();}).show();}
    private void delete(Order o){new AlertDialog.Builder(this).setTitle("🗑️ Удалить заказ?").setMessage(o.address+"\n\n"+money.format(o.total)+" ₽ • "+dist(o.km)).setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->{orders.remove(o);save();refresh();toast("Заказ удалён");}).show();}
    private void clear(){new AlertDialog.Builder(this).setTitle("Очистить заказы?").setMessage("Все сохранённые заказы будут удалены. Тарифы останутся.").setNegativeButton("Отмена",null).setPositiveButton("Очистить",(d,w)->{orders.clear();save();refresh();}).show();}

    private void settings(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),0,dp(18),0);EditText a=field("Забор, ₽",true),b=field("Доставка, ₽",true),c=field("Тариф за км, ₽",true),g=field("Тариф за кг, ₽",true),r=field("Рейтинг",true),x=field("Бонус 5.00",true),y=field("Бонус 4.75–4.99",true),z=field("Бонус 4.50–4.74",true),q=field("Бонус 4.25–4.49",true);a.setText(money.format(pickup));b.setText(money.format(delivery));c.setText(money.format(perKm));g.setText(money.format(perKg));r.setText(String.valueOf(rating));x.setText(money.format(r5));y.setText(money.format(r475));z.setText(money.format(r450));q.setText(money.format(r425));for(EditText e:new EditText[]{a,b,c,g,r,x,y,z,q})box.addView(e,mw());box.addView(tv("ℹ️ Адреса вводятся вручную. Километраж вводится вручную с точностью до метра. Автопоиск маршрута отключён.",13,false),mw());new AlertDialog.Builder(this).setTitle("⚙️ Настройки").setView(box).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",(d,w)->{pickup=parse(a.getText().toString(),pickup);delivery=parse(b.getText().toString(),delivery);perKm=parse(c.getText().toString(),perKm);perKg=parse(g.getText().toString(),perKg);rating=clamp(parse(r.getText().toString(),rating),0,5);r5=parse(x.getText().toString(),r5);r475=parse(y.getText().toString(),r475);r450=parse(z.getText().toString(),r450);r425=parse(q.getText().toString(),r425);prefs.edit().putString(PICKUP,""+pickup).putString(DELIVERY,""+delivery).putString(PKM,""+perKm).putString(PKG,""+perKg).putString(RATING,""+rating).putString(R5,""+r5).putString(R475,""+r475).putString(R450,""+r450).putString(R425,""+r425).apply();refresh();}).show();}

    private void loadOrders(){String raw=prefs.getString(ORDERS,"");if(raw.isEmpty())return;try{JSONArray a=new JSONArray(raw);for(int i=0;i<a.length();i++){JSONObject j=a.getJSONObject(i);orders.add(new Order(j.optDouble("total"),j.optDouble("km"),j.optDouble("kg"),j.optString("store"),j.optString("address"),j.optDouble("rating",rating),j.optDouble("ratingBonus"),j.optDouble("weightBonus"),j.optBoolean("multi"),j.optBoolean("multiFirst",true)));}}catch(Exception ignored){}}
    private void save(){JSONArray a=new JSONArray();for(Order o:orders){try{JSONObject j=new JSONObject();j.put("total",o.total);j.put("km",o.km);j.put("kg",o.kg);j.put("store",o.store);j.put("address",o.address);j.put("rating",o.rating);j.put("ratingBonus",o.ratingBonus);j.put("weightBonus",o.weightBonus);j.put("multi",o.multi);j.put("multiFirst",o.multiFirst);a.put(j);}catch(Exception ignored){}}prefs.edit().putString(ORDERS,a.toString()).apply();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private static class Store{final String name,address;Store(String n,String a){name=n;address=a;}}
    private static class Row{EditText address,kg,km;}
    private static class Order{final double total,km,kg,rating,ratingBonus,weightBonus;final String store,address;final boolean multi,multiFirst;Order(double t,double k,double g,String s,String a,double r,double rb,double wb,boolean m,boolean f){total=t;km=k;kg=g;store=s;address=a;rating=r;ratingBonus=rb;weightBonus=wb;multi=m;multiFirst=f;}}
}
